### ISSUE TITLE
Can only load js from head

### ISSUE THREAD

**Issue by legos** [jney/jquery.pageless#2] opened 2010-11-10 05:10 UTC
How can I get the JS to load from the body? I'm optimizing my site so all JS is loaded last (before the closed body tag) but the endless js doesn't seem to want to work when placed there. Any suggestions? 

Thanks

**Comment by jney** [comment] 2010-11-10 17:48
i just made a test loading jquery, pageless and then calling the function just closing _body_ tag and it works just fine for me.
do you have an example page ?

**Comment by legos** [comment] 2010-11-10 18:03
Sure, I've setup a demo and set the pagination to 3 per page - in theory this should be using the ajax call however I see the normal pagination. The url is http://planepieces.unruehly.com/categories/apparel-decals-posters

The code I'm using in my default template is as follows, when placed before </body> the pagination does not work. 

<%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js', 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/jquery-ui.min.js', 'jrails', 'application' %>  
<% if controller.controller_name == 'categories' and controller.action_name == 'show' %>
<%= javascript_include_tag 'jquery.endless' %>
<% end %>

**Comment by jney** [comment] 2010-11-10 18:47
the problem is that you call `pageless`function before you call jquery and pageless scripts in your page : even jQuery is not set :

```
$ is not defined
http://.../apparel-decals-posters
Line 97
```

Put the function call after the script calls. Actually i would even recommend you to put this function in an external script where you load your specific javascript, and you launch it when `ready` is triggered.

```
(function ($) {
  $('#results').pageless({"url":"/categories/apparel-decals-posters","totalPages":2,"loaderMsg":"Fetching More Products"});
  // other code come here
})(jQuery);
```

**Comment by jney** [comment] 2010-11-11 13:17
not a pageless bug

**Closed as completed by jney** 2010-11-11 13:17 UTC
